### PR TITLE
B#20: web-ifc Property Editing Tutorial

### PR DESCRIPTION
**Pull request by HassanEmam**

### CODE REVIEW

**Comment by agviegas** [comment]
Fantastic work @HassanEmam! Now, to get your money, you need to submit an expense to [IFC.js Open Collective](https://opencollective.com/ifcjs) with the price of the bounty. 

Once the expense is created, you need to tell us the invoice number using the `expense` command with the ID of the expense. You can see an example [here](https://github.com/IFCjs/info/issues/65#issuecomment-1202267147).

**Comment by HassanEmam** [comment]
Thanks @agviegas I have submitted the expense and I will follow the steps

**Comment by HassanEmam** [comment]
::expense::91978

**Comment by agviegas** [comment]
Hey @HassanEmam you need to use that command in the issue, not the PR :)

**Pull request merged**
